### ISSUE TITLE
Fix text showing up on image

### ISSUE THREAD

**Issue by VickiLanger** [VickiLanger/LGBTQ-of-the-day-bot#109]
**Describe the bug**
Image text should be centered-ish and have space to breathe. Currently lines spacing and margins are non-existant

**Expected behavior**
Words should be legible, with space between lines and kinda in the center

It should be fixable in this file: https://github.com/VickiLanger/LGBTQ-of-the-day-bot/blob/production/get_img_for_tweet.py

**Screenshots**
![Screen Shot 2020-10-19 at 9 17 20 PM](https://user-images.githubusercontent.com/46823403/96528518-f8747f00-1250-11eb-8939-3d191ec098a3.png)
![Screen Shot 2020-10-19 at 9 17 27 PM](https://user-images.githubusercontent.com/46823403/96528519-f8747f00-1250-11eb-80a8-e69bf00edc37.png)
![Screen Shot 2020-10-19 at 9 17 40 PM](https://user-images.githubusercontent.com/46823403/96528520-f90d1580-1250-11eb-8443-18158be2ed69.png)

**Additional context**

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/LGBTQotd) to see the hard work you put in.*

**Comment by misterdabu** [comment]
I'll work on this if you don't mind.

**Comment by VickiLanger** [comment]
Sounds great @misterdabu. I look forward to seeing your PR.

**Comment by Ares358** [comment]
I think this issue should be closed if #116 completely solved it.
