### ISSUE TITLE
Add More Background Images

### ISSUE THREAD

**Issue by VickiLanger** [VickiLanger/LGBTQ-of-the-day-bot#147]
_This will be a running issue to let people know how to add more images to the `img_bg` directory_

---

Make and add some backgrounds to be used at random for posting on [@LGTBTotd on twitter](twitter.com/LGBTQotd)

### Requirements for Consistency
- in one of the standard fonts, include twitter handle `@LGBTQotd` somewhere on the image
- Keep the file name convention. Just numbers like `101` or numbers with the letter 'a' like `101a`.
- Must adhere to WCAG accessibility standards for contrast and color blindness with `#0b3c49` a dark blue as the text that will be on them.
- Dimensions should be `1600 x 900`  `16:9`

#### Standard Fonts 
- [Comfortaa](https://fonts.google.com/specimen/Comfortaa?query=comf&selection.family=Comfortaa)
- [Pompiere](https://fonts.google.com/specimen/Pompiere?query=pomp&selection.family=Pompiere)
- [Nunito](https://fonts.google.com/specimen/Nunito?query=nun&selection.family=Nunito)
([link to all three fonts](https://fonts.google.com/specimen/Pompiere?query=pomp&selection.family=Comfortaa|Nunito|Pompiere))

#### Standard Colors
- `#0b3c49` a dark blue
- `#f2a130` an orangey yellow
- `#444444` a dark gray
- `#86b500` greenish
- `#f4f4f4` almost white, kinda gray

### Proposed workflow:
1. Fork this repo
2. Add images to `img_bg` keeping to the existing naming conventions:
   * Each image should have the twitter handle and meet accessibility standards
   * follow the examples in `img_bg` 
3. Once you are done and checked for typos, commit it & push your work to your fork
4. Submit a PR against this repo

Someone will look it over and, if deemed appropriate, will merge your PR.

Thanks for contributing!

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/LGBTQotd) to see the hard work you put in.*

**Comment by aditisingh2412** [comment]
Hello @VickiLanger I'm a first-timer. I am interested in contributing to this issue.

**Comment by VickiLanger** [comment]
@aditisingh2412 I look forward to seeing your pull request.

**Comment by wasabi28** [comment]
Hi, I want to contribute to the issue.

**Comment by VickiLanger** [comment]
@wasabi28  I look forward to seeing your pull request.

**Comment by dianamenesesg** [comment]
Hi @VickiLanger! I would like to contribute with my PR as well.

**Comment by thomasneil** [comment]
Hi @VickiLanger May I contribute to this as well?

**Comment by JasirZaeem** [comment]
@VickiLanger Image size is currently assumed to be 1600 x 900 in the script to generate images, if and until that is changed Dimensions of images being added should only be 1600 x 900 so "Dimensions should be 1200 x 675, 16:9 or equivalent" should be changed to tell contributors adding new images the same.

**Comment by VickiLanger** [comment]
Thanks, @JasirZaeem. Fixed.

**Comment by prankurverma** [comment]
Hey @VickiLanger Can I contribute to this as well?

**Comment by prankurverma** [comment]
> Hey @VickiLanger Can I contribute to this as well?

Am I also supposed to add that translucent box with twitter handle?

**Comment by VickiLanger** [comment]
@prankurverma It's not required. The most important part is being accessible. So, if there is enough contrast between the background and the `#0b3c49` text that will be on the background, then the translucent box isn't needed. I'm open to anything that still adhere's to WCAG accessibility standards

**Comment by prankurverma** [comment]
> @prankurverma It's not required. The most important part is being accessible. So, if there is enough contrast between the background and the `#0b3c49` text that will be on the background, then the translucent box isn't needed. I'm open to anything that still adhere's to WCAG accessibility standards

I believe the box is added by some automation or template? Is it fine if I simply add my created background? Or is the box template included in this repo?

**Comment by VickiLanger** [comment]
> > @prankurverma It's not required. The most important part is being accessible. So, if there is enough contrast between the background and the `#0b3c49` text that will be on the background, then the translucent box isn't needed. I'm open to anything that still adhere's to WCAG accessibility standards
> 
> I believe the box is added by some automation or template? Is it fine if I simply add my created background? Or is the box template included in this repo?

The box was manually placed on each background. I built the first 100 or so files with canvas. Design and stuff isn't really my thing. [an example background image](https://github.com/VickiLanger/LGBTQ-of-the-day-bot/blob/production/img_bg/1.png)

**Comment by prankurverma** [comment]
Hey @VickiLanger ! I've made a PR #224 for this issue. :)

**Comment by VickiLanger** [comment]
WOrking on automating images to make sure images are legit accessible and consistent 

#265
