### ISSUE TITLE
Non specific dates for lgbtq history

### ISSUE THREAD

**Issue by LL-creator** [VickiLanger/LGBTQ-of-the-day-bot#171]
**Is your feature request related to a problem? Please describe.**
Although I understand that for the dictionary it would be good to have specific dates to look-up to find facts, 
doing that leaves out a lot of other LGBTQ history. Especially those before the common era (BCE).

**Describe the solution you'd like**
I would like to see either another dictionary containing only centuries as the key or allow nonspecific dates for keys on the original dictionary.

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/LGBTQotd) to see the hard work you put in.*

**Comment by VickiLanger** [comment]
Thanks for bringing this up. I have thought about events with nonspecific dates before. I'm not sure how they would work though. 

The events are used so they can be tweeted on their anniversary date. So, an event that happens today, if added to the dictionary, would then be tweeted on this day next year.

I'm open to all ideas. Let me know what you think we could do with events that have nonspecific dates

**Comment by VickiLanger** [comment]
I appreciate the idea. Without further input, I will not be moving forward with this
