### ISSUE TITLE
Add generating images for posts

### ISSUE THREAD

**Issue by VickiLanger** [VickiLanger/LGBTQ-of-the-day-bot#2]
Add images that generate when posting. I think it's something to do with open graph. **Must have alt text**

Both dev.to and webwide have this.

Maybe this is the wizardry behind it? https://lannonbr.com/blog/2019-11-10-og-images/

Images are in `img_bg` folder.
![](https://pbs.twimg.com/media/EitBKMpXYAINwXh?format=jpg&name=medium)

Thanks for contributing!
---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/LGBTQotd) to see the hard work you put in.*

**Comment by iriyagupta** [comment]
Hi ! Can you explain this a bit? @VickiLanger

**Comment by VickiLanger** [comment]
Absolutely, @iriyagupta.  Right now, `tweet.py` sends a string `f"today's queerness is a {adjective} {label} {noun}"` to Twitter. I'd like for this string to show up on a random image from the `img_bg` folder.

I have no clue how to generate the image and I've put very little thought into how it could be done.

Ways I've thought about doing it:

1. This [twitter bot](https://twitter.com/colorschemez/status/1310387639732768768?s=20) by @joemfox generates images, though I'm not sure how. I haven't looked. [that bot's repo](https://github.com/joemfox/colorschemer)
2. Lots of sites like webwide.io and dev.to have images that generate when links are posted. I don't want links, but I'm sure similar could be done. They're doing it with open graph, I think.

**Comment by iriyagupta** [comment]
@VickiLanger So is it like if the image with a text is already available let us say the text is "Today's queerness is a purring biromantic walkman" it should also generate the image 98 which is containing the same text or if the text is not available on the image from the img_bg folder, you want any random image with no text on it to appear and display the string sent by tweet.py?

**Comment by VickiLanger** [comment]
@iriyagupta The images in the folder are all blank. I'd like it to grab a random image and show the string on the image

**Comment by iriyagupta** [comment]
@VickiLanger Oh okay, understandable. I will give it a try

**Comment by iriyagupta** [comment]
@VickiLanger do we have a registered consumer key for the application? Or shall I create my own

**Comment by VickiLanger** [comment]
@iriyagupta I have keys. I'm not sure how to share them without sharing them publically. I think you should be able to use `authenticate_api` from `tweet.py` https://github.com/VickiLanger/Queer-of-the-day-bot/blob/production/tweet.py.

**Comment by iriyagupta** [comment]
@VickiLanger Without keys authenticate_api doesn't seem to work, is there anywhere we can share them?

**Comment by VickiLanger** [comment]
You're right. It won't work locally without the keys. Sharing keys poses a security risk. It would be best to get keys of your own, if need be. I got my keys through https://developer.twitter.com/en/apps

reference: https://twitter.com/grahamcox82/status/1311742466429722626?s=20

**Comment by iriyagupta** [comment]
@VickiLanger So I have applied for twitter developer account but it will take some time to get accepted, before that I won't be able to run this due to the lack of auth key

**Comment by VickiLanger** [comment]
Sounds great. I understand

**Comment by tahazanzibarwala** [comment]
@VickiLanger are you facing an issue posting an image to Twitter or generating the image with the text itself?

**Comment by VickiLanger** [comment]
@tahazanzibarwala Generating the image itself

**Comment by AhmedOssama22dev** [comment]
Hey @VickiLanger , i wrote some utility functions that may help and with very few **customizations** you can change the font:style,color,size and the positions.
The methods do the following:1]Choose a random image from img_bg folder
2]Write text on the image in the blank area. [text are classified into -short ,-long]
3]The image object is returned for any operations also its name for saving it locally in the current dir.
I hope my code may help you =)
#78
