### ISSUE TITLE
Randomize Fonts used in to Create Images

### ISSUE THREAD

**Issue by VickiLanger** [VickiLanger/LGBTQ-of-the-day-bot#203]
**Describe the enhancement you'd like**
Currently `get_img_for_tweet.py` uses one font to build the images posted on [Twitter.com/LGBTQotd](Twitter.com/LGBTQotd). It would be great if we could use a random font from `assets`.

This will require a new file.

https://github.com/VickiLanger/LGBTQ-of-the-day-bot/tree/production/assets
https://github.com/VickiLanger/LGBTQ-of-the-day-bot/blob/production/get_img_for_tweet.py

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/LGBTQotd) to see the hard work you put in.*

**Comment by tejusrevi** [comment]
@VickiLanger I can try to do that

**Comment by Harivind** [comment]
Hi, I would like to take up this issue!

**Comment by tejusrevi** [comment]
If its okay with two members working on the same issue, I would also like to work towards solving this

**Comment by VickiLanger** [comment]
I have yet to see more than one person work on the same issue and have it go well. Though, I see you already put in a PR. I'll check it out @tejusrevi
