### ISSUE TITLE
tweet_historical_event() in tweet_historical_events.py needs some tweaks to be functional

### ISSUE THREAD

**Issue by bobsany16** [VickiLanger/LGBTQ-of-the-day-bot#38]
**Describe the bug**
Right now, the `tweet_historical_event()` function in `tweet_historical_events.py` only generates the tweet when the `today`'s date (YYYY-MM-DD) matches exactly that in the `events` list. 

**To Reproduce**
1. Go to `tweet_historical_events.py`
2. Scroll down to 'tweet_historical_event()' on line 46
4. See error -> can be followed along by just reading or work in Jupyter notebook to see error by copying the `events` list and the function. 

**Expected behavior**

- Let's say today is 2020-06-28, ideally I would see a tweet about the Stonewall Riots since the date and month matches that of the event (**go to line 18**)
- However, since there are no conditions to **only check date and month**, the function `tweet_historical_events()` does not return anything. 

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 10.15.7

**Additional context**
- Also, a conditional statement to handle multiple events on the same date would be necessary - what if there are 2 major events on the same date and month but different years ? 
- I can make a PR for this :) 

---

**Comment by bobsany16** [comment]
I'm working on this, just waiting for current PRs to merge before submitting a PR for this. This is so exciting 😁👌🤯

**Comment by VickiLanger** [comment]
I'm going through and merging everything now.

**Comment by bobsany16** [comment]
Thanks for getting back to me! I saw that somebody else has submitted a PR for this #42 . The only difference between my solution (no PR yet) is that when there are multiple events on the same date, it would generate it randomly. Would you still want me to submit a PR for you to see ? @VickiLanger

**Comment by VickiLanger** [comment]
I left that one for last because I didn't want to ignore that you were working on it. I like the idea of having it randomly choose if there are multiple events. That makes sense.
@bobsany16

**Comment by bobsany16** [comment]
ah thank you! I'll have a PR up soon :) @VickiLanger

**Comment by VickiLanger** [comment]
It's new to me to have multiple PRs for the same issue. Should I merge their PR or just take your's when you submit it?

**Comment by bobsany16** [comment]
I'm sorry if it's somewhat overwhelming! Well, I think you should merge their changes (they should resolve the conflict before you merge) just so their contribution doesn't get wasted. Then I'll just update my local repo and put in my changes then make a PR.

**Comment by VickiLanger** [comment]
You're not overwhelming. It's just new to me. 

I actually just closed their PR. You had already created the issue. Their contribution was after you'd identified the issue and said you'd work it.

**Comment by bobsany16** [comment]
It's new to me as well so I know how you feel! You're doing great. Please please let me know if I can be of any extra help! I'm glad to contribute and stuffs 👌. PR is up.
