### ISSUE TITLE
Organize historical events by country

### ISSUE THREAD

**Issue by franciellyferreira** [VickiLanger/LGBTQ-of-the-day-bot#44]
**Is your feature request related to a problem? Please describe.**
The history of LGBTQ+ rights in the world happened differently in different countries. I would like to propose
organization of historical events by countries, a way to show the chronological differences in the achievements in rights in different countries.

**Describe the solution you'd like**
I would like to standardize historical events with the names of the countries.

**Describe alternatives you've considered**
To carry out this modification it will be necessary to change the dictionary of 'events' and modify 'tweet_historicat_event' to add the name of the country in the tweet.

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/LGBTQotd) to see the hard work you put in.*

**Comment by franciellyferreira** [comment]
@VickiLanger Can I make this change?

**Comment by franciellyferreira** [comment]
I'm working on this improvement. 👍🏻

**Comment by meghanagottapu** [comment]
can I work on this issue? @VickiLanger

**Comment by VickiLanger** [comment]
@meghanagottapu 

@franciellyferreira is working this issue.

**Comment by franciellyferreira** [comment]
@VickiLanger I made the change by country, but I need you to pause the 'merge' of code submissions to 'historical_events', as we run the risk of missing events. I go send a Pull request.

**Comment by VickiLanger** [comment]
I apologize for the inconvenience. It ended up making more sense to organize by date.
