### ISSUE TITLE
Decide between a & an for proper grammar

### ISSUE THREAD

**Issue by VickiLanger** [VickiLanger/LGBTQ-of-the-day-bot#6]
`get_tweet.py`

**Is your feature request related to a problem? Please describe.**
Currently, the f'string isn't accounting for the proper use of `a` and `an`.
![Screenshot from @LGBTQotd twitter  "today's queerness is a slimy panromantic snek Snake", "today's queerness is a animated two-spirit pipe made out of an apple", "today's queerness is a obsolete demiromantic floppy disc"](https://user-images.githubusercontent.com/46823403/93777967-5f236000-fbf3-11ea-806e-efd1ad6dfa75.png)

**Describe the solution you'd like**
properly decide between  `a` and `an`.

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/LGBTQotd) to see the hard work you put in.*

**Comment by kandasamyc** [comment]
Can I work on this?

**Comment by hot9cups** [comment]
I'd like to work on this!

**Comment by VickiLanger** [comment]
As we discussed yesterday, @hot9cups would like to work this issue. @SamC302, if for some reason @hot9cups needs help or doesn't do it, it's all yours.
