### ISSUE TITLE
i am not able to understand what to do to do a successful pr in this repo mam

### ISSUE THREAD

**Issue by varanasiroshan2001** [VickiLanger/LGBTQ-of-the-day-bot#66]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/LGBTQotd) to see the hard work you put in.*

**Comment by VickiLanger** [comment]
If you would like to contribute, please review the [readme](https://github.com/VickiLanger/Queer-of-the-day-bot/blob/production/README.md) which has a section about contributing and then take a look at the issues.
