### ISSUE TITLE
tweet_nouns.py has a syntax error that might jeopardize the app

### ISSUE THREAD

**Issue by bobsany16** [VickiLanger/LGBTQ-of-the-day-bot#68]
**Describe the bug**
- Missing comma

**To Reproduce**
1. Go to tweet_nouns.py
2. See lines:
 

- `62`: comma inside string

Note:
---
I won't make a PR because there's only one syntax error. Someone who has a PR up should fix the comma :) 

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/LGBTQotd) to see the hard work you put in.*

**Comment by VickiLanger** [comment]
Thanks for bringing that up. I fixed `'seal',` and several others. One had `.` instead of a comma and some others didn't have their commas.
