### ISSUE TITLE
Add a reply tweet defining the label using in the initial tweet

### ISSUE THREAD

**Issue by VickiLanger** [VickiLanger/LGBTQ-of-the-day-bot#91]
**Describe the solution you'd like**

- Adjust `get_reply.py` to have definitions for each label OR have definitions in `tweet_labels.py`
- add definition for each label

**Additional context**
reply code in `tweet.py` needs to uncommented and adjusted as necessary

```python
def main():
    api = authenticate_api()
    #reply_with = get_reply()

    print("finding a tweet...")
    tweet = get_tweet()
    print("chose tweet: " + tweet)
    tweet = api.update_status(tweet)  # variable used later for reply to this tweet
    print('tweet has been tweeted')
    #api.update_status(status=reply_with, in_reply_to_status_id=tweet.id, auto_populate_reply_metadata=True)
    #print('chose reply:' + reply_with)
    #print('reply has been tweeted')


main()
```

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/LGBTQotd) to see the hard work you put in.*

**Comment by JasirZaeem** [comment]
I would like to have a go at this issue. I'll change the labels list into a dictionary, where the labels are the keys and their corresponding values are their definitions, then update get_reply to retrieve and reply with the definition of the label used in the original tweet.

**Comment by VickiLanger** [comment]
Sounds great. I look forward to seeing your PR. @JasirZaeem
